---
- name: Converge
  hosts: all
  tasks:
    - name: instalado GNU PG2
      apt:
        update_cache: yes
        name: gnupg2
        state: present

    - name: "Include iac-role-nomad"
      include_role:
        name: "iac-role-nomad"
      vars:
        # Módulos de kernal não estão disponíveis dentro de container.
        nomad_cni_enable_kernel_module: false
