name: "Valida role ansible"
  
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  valida:
    uses: "mentoriaiac/cicd_centralizado/.github/workflows/ansible_valida_role.yaml@v1"
    secrets:
      token: ${{ secrets.TOKEN }}
